export const GARMENT_ICONS: Record<string, string> = {
  // Men
  'Shirt': '👔',
  'T-Shirt': '👕',
  'Track Pant / Lower': '👖',
  'Pajama': '🌙',
  'Kurta': '🥻',
  'Dhoti': '🩳',
  'Suit (2-Piece)': '🤵',
  'Suit (3-Piece)': '🤵',
  'Jeans': '👖',
  'Trouser': '👖',
  'Half Pant / Shorts': '🩳',
  'Sherwani': '👘',
  'Jacket': '🧥',
  'Coat / Blazer': '🧥',
  'Waist Coat': '🎩',
  'Safari Suit': '🕶️',
  'Track Suit (Set)': '🏃',
  'Sweater': '🧣',
  'Sweat Shirt': '👕',
  'Hoodie': '🎽',
  'Baniyan / Vest': '🩱',
  'Underwear': '🩲',
  'Socks (Pair)': '🧦',
  'Tie': '🎀',
  'Handkerchief': '🤲',
  'Muffler / Scarf': '🧣',
  'Cap / Hat': '🧢',

  // Women
  'Saree': '🥻',
  'Salwar Suit (Set)': '👘',
  'Lehenga (Set)': '👗',
  'Kurti': '👗',
  'Top / Blouse': '👚',
  'Gown': '👗',
  'Dupatta': '🧣',
  'Blouse': '👚',
  'Petticoat / Lining': '🩱',
  'Salwar / Churidar': '👖',
  'Palazzo': '👖',
  'Sharara': '👗',
  'Skirt': '🩱',
  'Maxi / Long Dress': '👗',
  'Mini / Short Dress': '👗',
  'Night Suit (Set)': '🌙',
  'Stole': '🧣',
  'Shawl': '🧣',
  'Cardigan': '🧥',
  'Scarf': '🧣',
  'Inner Wear': '🩲',
  'Half Saree (Set)': '🥻',
  'Anarkali Suit': '👗',
  'Jumpsuit': '🦸',

  // Kids
  'Kids Shirt': '👕',
  'Kids T-Shirt': '👕',
  'Kids Lower / Track Pant': '👖',
  'Kids Jeans': '👖',
  'Kids Kurta': '🥻',
  'Kids Pajama': '🌙',
  'Kids Frock': '👗',
  'Kids Salwar Suit': '👘',
  'School Uniform (Shirt)': '🏫',
  'School Uniform (Pant)': '👖',
  'Kids Track Suit (Set)': '🏃',
  'Kids Jacket': '🧥',
  'Kids Sweater': '🧣',
  'Kids Shorts': '🩳',
  'Kids Baniyan / Vest': '🩱',
  'Kids Underwear': '🩲',
  'Kids Socks (Pair)': '🧦',
  'Baby Clothes': '👶',
  'Kids Cap': '🧢',
  'Kids Tie': '🎀',

  // Household
  'Blanket (Single)': '🛏️',
  'Blanket (Double)': '🛏️',
  'Bed Sheet (Single)': '🛏️',
  'Bed Sheet (Double)': '🛏️',
  'Pillow Cover': '😴',
  'Bedspread / Bed Cover': '🛏️',
  'Sofa Cover (Per Piece)': '🛋️',
  'Curtain (Small)': '🪟',
  'Curtain (Large)': '🪟',
  'Table Cover / Cloth': '🍽️',
  'Carpet / Dhurrie': '🎨',
  'Bath Towel': '🚿',
  'Hand Towel': '🤲',
  'Face Towel': '😌',
  'Bath Mat': '🚿',
  'Door Mat': '🚪',
  'Quilt / Razai (Single)': '❄️',
  'Quilt / Razai (Double)': '❄️',
  'Cushion Cover': '🛋️',
  'Duvet Cover': '🛏️',
  'Car Seat Cover': '🚗',
  'Curtain Lining': '🪟',

  // Shoes
  'Sports Shoes': '👟',
  'Formal Shoes': '👞',
  'Casual Shoes': '👟',
  'Sandals': '🩴',
  'Loafers': '👞',
  'Boots (Ankle)': '👢',
  'Boots (Long)': '👢',
  'Sneakers': '👟',
  'Heels / Pumps': '👠',
  'School Shoes': '👞',
  'Canvas Shoes': '👟',
  'Kolhapuri / Traditional': '🩴',
  'Flip Flops / Slippers': '🩴',
  'Moccasins': '👞',

  // Others
  'Bag (Small)': '👜',
  'Bag (Large)': '👜',
  'Purse / Handbag': '👛',
  'Backpack': '🎒',
  'Helmet': '⛑️',
  'Soft Toy (Small)': '🧸',
  'Soft Toy (Large)': '🧸',
  'Gloves (Pair)': '🧤',
  'Belt': '🔗',
  'Umbrella': '☂️',
  'Fancy Dress Costume': '🎭',
  'Gym Bag / Duffel': '💼',
  'Wallet': '👝',
  'Stuffed Animal': '🧸',
};
